# load biến môi trường từ file .env hoặc .env.properties nếu có
spring.config.import=optional:file:.env[.properties]

spring.application.name=pharmacywebsite
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pharmacywebsite}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# tự động cập nhật các thay đổi trên entity
spring.jpa.hibernate.ddl-auto=update 

# Bật các log sql
# spring.jpa.show-sql=true
# tắt các log sql
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Không hiển thị trace trong response mặc định của Spring Boot
server.error.include-stacktrace=never

app.jwt.secret=your_jwt_secret_key_123
spring.jmx.enabled=false

# VNPAY sandbox config
vnpay.tmnCode=ZT3TNUY4
vnpay.secretKey=2GOB16AK6PXUVJ6HQ19ACYCPKQ4ZI4S9
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/v1/payment/vnpay-return
vnpay.apiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# Cấu hình đường dẫn lưu file
# Tạo thư mục 'uploads' và 'categories' bên trong 'uploads' 
# (ngang hàng với 'src' và 'target')
file.upload-dir=uploads/categories

# Cấu hình dung lượng file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ---- Gemini (Google GenAI) ----
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
spring.ai.google.genai.chat.options.temperature=0.2
# spring.ai.google.genai.api-key=${GEMINI_API_KEY}
# spring.ai.google.genai.chat.options.model=gemini-2.0-flash
# spring.ai.google.genai.chat.options.temperature=0.2
# spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/

spring.ai.openai.api-key=${gemini.api.key}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-1.5-flash
spring.ai.openai.chat.options.temperature=0.7

gemini.api.key=AIzaSyB5aHN3kv418YTPWlm51DKJR00wumowgp0
